### ISSUE TITLE
OpenGL编译的bug

### ISSUE THREAD

**Issue by anvenle** [THU-luvision/XScale-NVS#10]
谢谢作者贡献的论文与工作，在执行ray caching那一步的时候，我这里有一个编译报错，然后找了一下解决方法，，还是没有具体解决，nvdiffrast document（https://nvlabs.github.io/nvdiffrast/#rasterizing-with-cuda-vs-opengl-new）有提到说：
1.Since version 0.3.0, nvdiffrast on PyTorch supports executing the rasterization operation using either CUDA or OpenGL. Earlier versions and the Tensorflow bindings support OpenGL only. 
2.To run rasterization in CUDA, create a RasterizeCudaContext and supply it to the rasterize() operation. For OpenGL, use a RasterizeGLContext instead. Easy!
具体做法我应该怎么做呢
![568f8c179e82e76dabf0dd91ca18db3](https://github.com/THU-luvision/XScale-NVS/assets/147358581/ce01c08a-8197-41e6-a481-d64d9f8a3be5)
![905d9eacc0c0bfcdb278df2bc364c1d](https://github.com/THU-luvision/XScale-NVS/assets/147358581/5bc5f7c1-2e72-4583-8128-e3f14b2447ce)

**Comment by luciancosw** [comment]
Hi @anvenle,

I think this issue is related to the compilation of [nvdiffrac](https://github.com/NVlabs/nvdiffrast). And we have never seen this problem on our devices. Please check the existing issues at the official repo (https://github.com/NVlabs/nvdiffrast/issues) to see if there are any similar problems.
